name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-test-build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      # 1. Checkout koda
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.12
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      # 3. Instaliraj zavisnosti
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest flake8

      # 4. Lint korak (provera stila koda)
      - name: Run lint
        run: flake8 .

      # 5. Test korak (pytest)
      - name: Run tests
        run: pytest

      # 6. Build korak (provera Docker image-a)
      - name: Build Docker image
        run: docker build -t backend-app .
